// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoayadAPI.Models
{
    public partial class ItemsBalance
    {
        public int ItemBalId { get; set; }
        public string ItemBalName { get; set; }
        public string ItemBalType { get; set; }
        public string ItemBalAmount { get; set; }
        public int? UserId { get; set; }

        public virtual UserInfo User { get; set; }
    }
}