// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoayadAPI.Models
{
    public partial class Privilage
    {
        public int PrivilageId { get; set; }
        public int? UserId { get; set; }

        public virtual UserInfo User { get; set; }
    }
}