// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoayadAPI.Models
{
    public partial class Store
    {
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public string StoreMaster { get; set; }
        public string StorePlace { get; set; }
        public string StorePhone { get; set; }
        public int? UserId { get; set; }

        public virtual UserInfo User { get; set; }
    }
}